"""The ``cards_json`` -> rows migration must not cost a single review.

``flashcard_reviews.card_id`` holds ``"{deck_id}:{index}"``, generated by the
blob-era ``generate_deck``. Migrated cards carry that exact string as
``card_ref``, so the reviews table is neither read nor rewritten here and every
card keeps the FSRS state it earned.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from backend.core.db import connect, init_schema, reset_schema_cache

FUTURE = "2099-01-01T00:00:00+00:00"


def _legacy_deck(conn: sqlite3.Connection, course: str = "CS201") -> int:
    """A deck exactly as the pre-rows code wrote it, plus one review.

    Ends by forgetting that this process has already brought the database up to
    schema, because that is what these tests are actually simulating: a
    database an older Argus wrote, opened by a newer one that has never seen
    it. `init_schema` only runs its DDL and migrations once per database per
    process, so without this the second call in each test below would rightly
    skip work this process had already done -- and the rows would only look
    unmigrated because the test reached behind it and wrote them.
    """
    cursor = conn.execute(
        "INSERT INTO flashcard_decks (course, title, cards_json) VALUES (?, ?, ?)",
        (course, f"{course} flashcards", "[]"),
    )
    deck_id = int(cursor.lastrowid)
    cards = [
        {"id": f"{deck_id}:0", "front": "big-O of merge sort", "back": "$O(n \\log n)$"},
        {"id": f"{deck_id}:1", "front": "is merge sort stable?", "back": "yes"},
    ]
    conn.execute(
        "UPDATE flashcard_decks SET cards_json = ? WHERE id = ?", (json.dumps(cards), deck_id)
    )
    conn.execute(
        "INSERT INTO flashcard_reviews"
        " (card_id, deck_id, grade, state, step, stability, difficulty, due_at, last_review_at)"
        " VALUES (?, ?, 'good', 2, 0, 12.5, 4.75, ?, NULL)",
        (f"{deck_id}:0", deck_id, FUTURE),
    )
    conn.commit()
    reset_schema_cache()
    return deck_id


def test_migration_creates_a_row_per_card_keyed_to_its_reviews(tmp_path: Path) -> None:
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    deck_id = _legacy_deck(conn)

    init_schema(conn)  # the migration runs here

    rows = conn.execute(
        "SELECT card_ref, front, back, position FROM flashcard_cards"
        " WHERE deck_id = ? ORDER BY position",
        (deck_id,),
    ).fetchall()
    assert [row["card_ref"] for row in rows] == [f"{deck_id}:0", f"{deck_id}:1"]
    assert rows[0]["front"] == "big-O of merge sort"
    assert rows[0]["back"] == "$O(n \\log n)$"
    assert [row["position"] for row in rows] == [0, 1]


def test_migration_leaves_review_history_attached(tmp_path: Path) -> None:
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    deck_id = _legacy_deck(conn)

    init_schema(conn)

    review = conn.execute(
        "SELECT r.stability, r.difficulty, r.due_at FROM flashcard_reviews r"
        " JOIN flashcard_cards c ON c.card_ref = r.card_id AND c.deck_id = r.deck_id"
        " WHERE c.position = 0 AND c.deck_id = ?",
        (deck_id,),
    ).fetchone()
    assert review is not None, "the review no longer joins to its card"
    assert review["stability"] == 12.5
    assert review["difficulty"] == 4.75
    assert review["due_at"] == FUTURE


def test_migration_is_idempotent(tmp_path: Path) -> None:
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    deck_id = _legacy_deck(conn)

    for _ in range(3):
        init_schema(conn)

    count = conn.execute(
        "SELECT COUNT(*) AS n FROM flashcard_cards WHERE deck_id = ?", (deck_id,)
    ).fetchone()["n"]
    assert count == 2, "a re-run duplicated the deck's cards"


def test_migration_skips_a_deck_whose_blob_is_unreadable(tmp_path: Path) -> None:
    """A hand-edited blob must not take down every database open."""
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    conn.execute(
        "INSERT INTO flashcard_decks (course, title, cards_json) VALUES ('CS1', 't', '{ not json')"
    )
    good = _legacy_deck(conn, "CS202")
    conn.commit()

    init_schema(conn)

    # The readable deck still migrated.
    assert (
        conn.execute(
            "SELECT COUNT(*) AS n FROM flashcard_cards WHERE deck_id = ?", (good,)
        ).fetchone()["n"]
        == 2
    )


def test_migration_drops_a_half_written_card(tmp_path: Path) -> None:
    """A card missing either face is not a card. It must not become a row."""
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    cursor = conn.execute(
        "INSERT INTO flashcard_decks (course, title, cards_json) VALUES (?, ?, ?)",
        ("CS203", "CS203 flashcards", "[]"),
    )
    deck_id = int(cursor.lastrowid)
    conn.execute(
        "UPDATE flashcard_decks SET cards_json = ? WHERE id = ?",
        (
            json.dumps(
                [
                    {"id": f"{deck_id}:0", "front": "kept", "back": "yes"},
                    {"id": f"{deck_id}:1", "front": "no answer", "back": ""},
                ]
            ),
            deck_id,
        ),
    )
    conn.commit()
    reset_schema_cache()  # see _legacy_deck: this is an upgrade, not a re-open

    init_schema(conn)

    refs = [
        row["card_ref"]
        for row in conn.execute(
            "SELECT card_ref FROM flashcard_cards WHERE deck_id = ?", (deck_id,)
        )
    ]
    assert refs == [f"{deck_id}:0"]


def test_new_deck_columns_default_sensibly(tmp_path: Path) -> None:
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    deck_id = _legacy_deck(conn)

    init_schema(conn)

    row = conn.execute(
        "SELECT source, source_paths, description, updated_at, created_at"
        " FROM flashcard_decks WHERE id = ?",
        (deck_id,),
    ).fetchone()
    # Everything that existed before decks could be authored was generated.
    assert row["source"] == "generated"
    assert row["description"] == ""
    # A constant default, so the ALTER fills the row itself -- no backfill line,
    # and a deck that predates the column honestly claims no sources.
    assert row["source_paths"] == "[]"
    # ALTER TABLE cannot take a non-constant default, so this is backfilled.
    assert row["updated_at"] == row["created_at"]


def test_match_scores_table_exists_and_cascades_from_its_deck(tmp_path: Path) -> None:
    conn = connect(tmp_path / "argus.db")
    init_schema(conn)
    deck_id = _legacy_deck(conn)

    conn.execute(
        "INSERT INTO flashcard_match_scores (deck_id, elapsed_ms, pairs) VALUES (?, ?, ?)",
        (deck_id, 18_400, 6),
    )
    conn.commit()

    row = conn.execute(
        "SELECT elapsed_ms, pairs FROM flashcard_match_scores WHERE deck_id = ?", (deck_id,)
    ).fetchone()
    assert row["elapsed_ms"] == 18_400
    assert row["pairs"] == 6
