"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useToast } from "@/components/Toast";
import ActivityChrome from "@/components/notebook/flashcards/ActivityChrome";
import CardFace from "@/components/notebook/flashcards/CardFace";
import { estimateMinutes } from "@/lib/flashcards/schedule";
import { gradeFlashcard, useDueCards, type DueCard, type FlashcardGrade } from "@/lib/api";

const GRADES: FlashcardGrade[] = ["again", "hard", "good", "easy"];

/** Sentence case, because these are words you read rather than chrome. */
const GRADE_LABEL: Record<FlashcardGrade, string> = {
  again: "Again",
  hard: "Hard",
  good: "Good",
  easy: "Easy",
};

const GRADE_STYLE: Record<FlashcardGrade, string> = {
  again: "border-nb-dangerLine text-danger hover:bg-nb-dangerBg",
  hard: "border-nb-warnLine text-warn hover:bg-nb-warnBg",
  good: "border-[var(--ac)] text-[var(--ac)] hover:bg-nb-acBg",
  easy: "border-nb-okLine text-ok hover:bg-nb-okBg",
};

interface Done {
  ref: string;
  grade: FlashcardGrade;
}

/** What the last grade actually bought, shown where the card was. */
interface Verdict {
  grade: FlashcardGrade;
  dueLabel: string;
}

/** The longest run of cards recalled without an `again`. */
function bestRun(done: Done[]): number {
  let best = 0;
  let run = 0;
  for (const entry of done) {
    run = entry.grade === "again" ? 0 : run + 1;
    if (run > best) best = run;
  }
  return best;
}

/** The current run, which is what the header pill counts. */
function currentRun(done: Done[]): number {
  let run = 0;
  for (const entry of done) run = entry.grade === "again" ? 0 : run + 1;
  return run;
}

/**
 * The scheduler of record.
 *
 * Three things separate this from the flip-and-grade screen it replaces.
 *
 * **Each grade button carries its real next interval** (`Good · Friday`),
 * computed by the backend from one FSRS state without committing any of them.
 * Four unlabelled verbs asked the user to guess what they cost; this does not.
 * The label is generated by the same function the commit reports back, so it
 * cannot drift — see `backend/features/flashcards/scheduler.py`.
 *
 * **The verdict is feedback on the grade you pressed, not a judgement of you.**
 * Review is self-graded and stays that way: nothing here marks an answer right
 * or wrong. Pressing Good says "Banked. Back on Friday"; pressing Again says
 * when it comes round. That is why the banner appears *after* a grade rather
 * than beside the answer — a "✓ Correct" before you have said anything would be
 * the app claiming to know something it does not.
 *
 * **It is keyboard-first.** Space flips, 1–4 grade, U undoes. A review session
 * is dozens of identical interactions in a row, which is exactly the shape that
 * should never require the mouse.
 */
export default function ReviewSession({
  deckId,
  deckTitle,
}: {
  deckId: number;
  deckTitle: string;
}) {
  const { data: due, mutate: refresh } = useDueCards(deckId);
  const { show } = useToast();

  const [queue, setQueue] = useState<DueCard[]>([]);
  const [flipped, setFlipped] = useState(false);
  const [done, setDone] = useState<Done[]>([]);
  const [verdict, setVerdict] = useState<Verdict | null>(null);
  const [grading, setGrading] = useState(false);
  const [startedAt] = useState(() => Date.now());

  // Seeded once, not on every identity change.
  //
  // `due` is SWR data, and nothing configures `revalidateOnFocus: false`, so
  // alt-tabbing away and back handed this a fresh array — and reset the queue
  // mid-session, re-inserting cards already graded in this sitting and
  // desyncing the `done.length + queue.length` total the progress bar reads.
  // A review session is a snapshot by nature: the point of `due` is what was
  // due when you sat down.
  const seeded = useRef(false);
  useEffect(() => {
    if (!due || seeded.current) return;
    seeded.current = true;
    setQueue(due);
  }, [due]);

  const current = queue[0];

  const grade = useCallback(
    async (value: FlashcardGrade) => {
      if (!current || grading) return;
      setGrading(true);
      try {
        const result = await gradeFlashcard(deckId, current.id, value);
        setDone((prev) => [...prev, { ref: current.id, grade: value }]);
        setQueue((prev) => prev.slice(1));
        setFlipped(false);
        setVerdict({ grade: value, dueLabel: result.due_label });
      } catch (error) {
        show(`grading failed: ${error instanceof Error ? error.message : "backend offline?"}`, {
          tone: "error",
        });
      } finally {
        setGrading(false);
      }
    },
    [current, deckId, grading, show],
  );

  /**
   * Undo re-grades the last card as `again`, which is the honest undo
   * available: a review is an append-only event, and putting the card back at
   * the front of the queue is what a misclick actually wants.
   */
  const undo = useCallback(async () => {
    const last = done[done.length - 1];
    if (!last || grading) return;
    setGrading(true);
    try {
      await gradeFlashcard(deckId, last.ref, "again");
      setDone((prev) => prev.slice(0, -1));
      setVerdict(null);
      await refresh();
      setFlipped(false);
      show("undone :: that card is due again now");
    } catch (error) {
      // `finally` without `catch` made a failed undo an unhandled rejection,
      // and left the session silent about it — the local state correctly did
      // not change, so the UI simply looked like nothing had happened.
      show(`undo failed: ${error instanceof Error ? error.message : "backend offline?"}`, {
        tone: "error",
      });
    } finally {
      setGrading(false);
    }
  }, [deckId, done, grading, refresh, show]);

  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      // Never steal a key from a field — the toast and the chrome both sit in
      // the same document as the deck editor's inputs on other routes.
      const target = event.target as HTMLElement | null;
      if (target && /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName)) return;

      if (event.key === " " || event.key === "Enter") {
        event.preventDefault();
        setFlipped((value) => !value);
        return;
      }
      if (event.key.toLowerCase() === "u") {
        event.preventDefault();
        void undo();
        return;
      }
      const index = Number(event.key);
      if (index >= 1 && index <= 4) {
        event.preventDefault();
        // Grading before the answer is visible is almost always a misfire.
        if (!flipped) {
          setFlipped(true);
          return;
        }
        void grade(GRADES[index - 1]);
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [flipped, grade, undo]);

  const total = done.length + queue.length;
  const again = done.filter((entry) => entry.grade === "again").length;
  const banked = done.length - again;
  const run = currentRun(done);

  if (!due) {
    return (
      <ActivityChrome deckId={deckId} deckTitle={deckTitle} activity="review">
        <p className="text-body text-nb-faint">Loading the queue…</p>
      </ActivityChrome>
    );
  }

  if (!current) {
    const minutes = Math.max(1, Math.round((Date.now() - startedAt) / 60000));
    return (
      <ActivityChrome deckId={deckId} deckTitle={deckTitle} activity="review">
        {done.length === 0 ? (
          <p className="text-body text-nb-faint">
            Nothing is due right now. Come back when a card comes up, or flip through the deck in
            Browse — that mode leaves your schedule alone.
          </p>
        ) : (
          <div className="rounded-card border border-nb-line bg-nb-panel p-7 text-center">
            {/* Tracking but no `uppercase`: the rest of this app writes its
                uppercase chrome as literal text, and a CSS transform makes the
                rendered string differ from the DOM's — which is a coin flip for
                anything matching on text, and reads as an initialism to some
                screen readers. */}
            <p className="text-label font-semibold tracking-[0.06em] text-ok">Session complete</p>
            <p className="mt-1 text-title font-semibold text-nb-ink">
              {done.length} card{done.length === 1 ? "" : "s"} in {minutes} minute
              {minutes === 1 ? "" : "s"}
            </p>

            {/* The last card's verdict, which would otherwise be the one you
                never get to read: grading the final card empties the queue and
                swaps the whole session out for this summary. */}
            {verdict && (
              <p className="mt-2.5 text-body text-nb-body">
                {GRADE_LABEL[verdict.grade]} — back in {verdict.dueLabel}.
              </p>
            )}

            <div className="mt-5 flex gap-2.5">
              <div className="flex-1 rounded-tile bg-nb-okBg p-3.5">
                <p className="text-title font-semibold text-ok">{banked}</p>
                <p className="mt-0.5 text-label text-nb-body">recalled</p>
              </div>
              <div className="flex-1 rounded-tile bg-nb-warnBg p-3.5">
                <p className="text-title font-semibold text-warn">{again}</p>
                <p className="mt-0.5 text-label text-nb-body">to see again</p>
              </div>
              <div className="flex-1 rounded-tile border border-nb-line p-3.5">
                <p className="text-title font-semibold text-nb-ink">{bestRun(done)}</p>
                <p className="mt-0.5 text-label text-nb-body">best run</p>
              </div>
            </div>

            <div className="mt-5 flex flex-wrap gap-2.5">
              {again > 0 && (
                <button
                  type="button"
                  onClick={() => {
                    // Cards graded `again` are due immediately, so the queue the
                    // server hands back already contains exactly those.
                    setDone([]);
                    setVerdict(null);
                    void refresh();
                  }}
                  className="flex-1 rounded-ctl bg-[var(--ac)] px-4 py-3 text-body font-semibold text-nb-onAc transition-opacity hover:opacity-90"
                >
                  Review the {again} again
                </button>
              )}
              <Link
                href={`/notebook/flashcards/${deckId}`}
                className="flex-1 rounded-ctl border border-nb-line px-4 py-3 text-body text-nb-ink transition-colors hover:border-nb-lineHi"
              >
                Back to the deck
              </Link>
            </div>
          </div>
        )}
      </ActivityChrome>
    );
  }

  return (
    <ActivityChrome
      deckId={deckId}
      deckTitle={deckTitle}
      activity="review"
      badge={
        done.length === 0 ? undefined : run > 0 ? (
          <span className="rounded-full bg-nb-okBg px-3 py-1 text-meta font-semibold text-ok">
            ● {run} in a row
          </span>
        ) : (
          <span className="rounded-full bg-nb-dangerBg px-3 py-1 text-meta font-semibold text-danger">
            run reset
          </span>
        )
      }
      progress={
        <>
          {done.length + 1}
          <span className="text-nb-faint"> / {total}</span>
        </>
      }
      segments={[
        { value: banked, tone: "ok" },
        { value: again, tone: "warn" },
        { value: queue.length, tone: "track" },
      ]}
      caption={`${banked} banked · ${again} to see again · about ${estimateMinutes(
        queue.length,
      )} minute${estimateMinutes(queue.length) === 1 ? "" : "s"} left`}
      keys="space flip · 1–4 grade · u undo"
    >
      {/* Feedback on the grade just pressed, where the eye already is. It
          replaces the toast this used to fire: a toast for something you do
          once per card is noise, and it left the screen before the interval
          could be read. */}
      {verdict && (
        <div
          className={`mb-3 flex flex-wrap items-center gap-2.5 rounded-tile border px-3.5 py-2.5 ${
            verdict.grade === "again"
              ? "border-nb-dangerLine bg-nb-dangerBg"
              : "border-nb-okLine bg-nb-okBg"
          }`}
        >
          <span
            className={`text-label font-semibold ${
              verdict.grade === "again" ? "text-danger" : "text-ok"
            }`}
          >
            {verdict.grade === "again" ? "✗ Not this time" : "✓ Banked"}
          </span>
          <span className="text-ctl text-nb-body">
            {GRADE_LABEL[verdict.grade]} — back in {verdict.dueLabel}.
          </span>
        </div>
      )}

      <CardFace
        front={current.front}
        back={current.back}
        hint={current.hint}
        flipped={flipped}
        onFlip={() => setFlipped((value) => !value)}
      />

      <button
        type="button"
        data-testid="flashcard-flip"
        aria-pressed={flipped}
        onClick={() => setFlipped((value) => !value)}
        className="mt-3 w-full rounded-ctl bg-[var(--ac)] py-3 text-body font-semibold text-nb-onAc transition-opacity hover:opacity-90"
      >
        {flipped ? "Show question" : "Show answer"}
        <span className="font-normal opacity-60"> · space</span>
      </button>

      <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">
        {GRADES.map((value, index) => (
          <button
            key={value}
            type="button"
            disabled={grading}
            onClick={() => void grade(value)}
            className={`rounded-ctl border px-1.5 py-2.5 text-center transition-colors disabled:opacity-70 ${GRADE_STYLE[value]}`}
          >
            {/* The number stays in the accessible name: it is the key that
                grades, and a test addressing "3 · Good" is addressing what a
                person reads on the button. */}
            <span className="block text-ctl font-semibold">
              {index + 1} · {GRADE_LABEL[value]}
            </span>
            {/* The real interval, not an adjective. This is what turns the bar
                into a choice rather than four unlabelled verbs. */}
            <span className="mt-0.5 block text-meta text-nb-faint">{current.preview[value]}</span>
          </button>
        ))}
      </div>

      {done.length > 0 && (
        <button
          type="button"
          onClick={() => void undo()}
          disabled={grading}
          className="mt-3 text-label text-nb-faint underline underline-offset-2 transition-colors hover:text-nb-ink disabled:opacity-70"
        >
          Undo last · <span className="font-mono">u</span>
        </button>
      )}
    </ActivityChrome>
  );
}
