"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useToast } from "@/components/Toast";
import ActivityChrome from "@/components/notebook/flashcards/ActivityChrome";
import CardFace from "@/components/notebook/flashcards/CardFace";
import { gradeFlashcard, useDueCards, type DueCard, type FlashcardGrade } from "@/lib/api";

const GRADES: FlashcardGrade[] = ["again", "hard", "good", "easy"];

const GRADE_STYLE: Record<FlashcardGrade, string> = {
  again: "hover:border-danger hover:text-danger",
  hard: "hover:border-amber-400 hover:text-amber-400",
  good: "hover:border-[var(--ac)] hover:text-[var(--ac)]",
  easy: "hover:border-ok hover:text-ok",
};

interface Done {
  ref: string;
  grade: FlashcardGrade;
}

/**
 * The scheduler of record.
 *
 * Two things separate this from the flip-and-grade screen it replaces.
 *
 * **Each grade button carries its real next interval** (`GOOD · 4d`), computed
 * by the backend from one FSRS state without committing any of them. Four
 * unlabelled verbs asked the user to guess what they cost; this does not. The
 * label is generated by the same function the commit reports back, so it
 * cannot drift — see `backend/features/flashcards/scheduler.py`.
 *
 * **It is keyboard-first.** Space flips, 1–4 grade, U undoes. A review session
 * is dozens of identical interactions in a row, which is exactly the shape
 * that should never require the mouse.
 */
export default function ReviewSession({
  deckId,
  deckTitle,
}: {
  deckId: number;
  deckTitle: string;
}) {
  const { data: due, mutate: refresh } = useDueCards(deckId);
  const { show } = useToast();

  const [queue, setQueue] = useState<DueCard[]>([]);
  const [flipped, setFlipped] = useState(false);
  const [done, setDone] = useState<Done[]>([]);
  const [grading, setGrading] = useState(false);
  const [startedAt] = useState(() => Date.now());

  useEffect(() => {
    if (due) setQueue(due);
  }, [due]);

  const current = queue[0];

  const grade = useCallback(
    async (value: FlashcardGrade) => {
      if (!current || grading) return;
      setGrading(true);
      try {
        const result = await gradeFlashcard(deckId, current.id, value);
        setDone((prev) => [...prev, { ref: current.id, grade: value }]);
        setQueue((prev) => prev.slice(1));
        setFlipped(false);
        show(`${value} :: back in ${result.due_label}`);
      } catch (error) {
        show(`grading failed: ${error instanceof Error ? error.message : "backend offline?"}`, {
          tone: "error",
        });
      } finally {
        setGrading(false);
      }
    },
    [current, deckId, grading, show],
  );

  /**
   * Undo re-grades the last card as `again`, which is the honest undo
   * available: a review is an append-only event, and putting the card back at
   * the front of the queue is what a misclick actually wants.
   */
  const undo = useCallback(async () => {
    const last = done[done.length - 1];
    if (!last || grading) return;
    setGrading(true);
    try {
      await gradeFlashcard(deckId, last.ref, "again");
      setDone((prev) => prev.slice(0, -1));
      await refresh();
      setFlipped(false);
      show("undone :: that card is due again now");
    } finally {
      setGrading(false);
    }
  }, [deckId, done, grading, refresh, show]);

  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      // Never steal a key from a field — the toast and the chrome both sit in
      // the same document as the deck editor's inputs on other routes.
      const target = event.target as HTMLElement | null;
      if (target && /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName)) return;

      if (event.key === " " || event.key === "Enter") {
        event.preventDefault();
        setFlipped((value) => !value);
        return;
      }
      if (event.key.toLowerCase() === "u") {
        event.preventDefault();
        void undo();
        return;
      }
      const index = Number(event.key);
      if (index >= 1 && index <= 4) {
        event.preventDefault();
        // Grading before the answer is visible is almost always a misfire.
        if (!flipped) {
          setFlipped(true);
          return;
        }
        void grade(GRADES[index - 1]);
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [flipped, grade, undo]);

  const total = done.length + queue.length;
  const again = done.filter((entry) => entry.grade === "again").length;

  if (!due) {
    return (
      <ActivityChrome deckId={deckId} deckTitle={deckTitle} activity="review">
        <p className="text-body text-ink-faint">Loading the queue…</p>
      </ActivityChrome>
    );
  }

  if (!current) {
    const minutes = Math.max(1, Math.round((Date.now() - startedAt) / 60000));
    return (
      <ActivityChrome deckId={deckId} deckTitle={deckTitle} activity="review">
        {done.length === 0 ? (
          <p className="text-body text-ink-faint">
            Nothing is due right now. Come back when a card comes up, or flip through the deck in
            FLASHCARDS — that mode leaves your schedule alone.
          </p>
        ) : (
          <div className="border border-line p-5">
            <p className="font-mono text-label uppercase tracking-[0.16em] text-[var(--ac)]">
              session complete
            </p>
            <p className="mt-2 text-lead text-ink-bright">
              {done.length} card{done.length === 1 ? "" : "s"} reviewed in ~{minutes} min
            </p>
            <p className="mt-1 font-mono text-label text-ink-muted">
              {done.length - again} recalled · {again} to see again
            </p>
            <Link
              href={`/notebook/flashcards/${deckId}`}
              className="mt-4 inline-block border border-line px-3 py-2 font-mono text-label uppercase tracking-[0.12em] text-ink-muted transition-colors hover:border-lineHi hover:text-ink"
            >
              back to the deck
            </Link>
          </div>
        )}
      </ActivityChrome>
    );
  }

  return (
    <ActivityChrome
      deckId={deckId}
      deckTitle={deckTitle}
      activity="review"
      progress={`${done.length + 1} / ${total}`}
      keys="space flip · 1–4 grade · u undo"
    >
      <CardFace
        front={current.front}
        back={current.back}
        hint={flipped ? null : current.hint}
        flipped={flipped}
        onFlip={() => setFlipped((value) => !value)}
      />

      <button
        type="button"
        data-testid="flashcard-flip"
        aria-pressed={flipped}
        onClick={() => setFlipped((value) => !value)}
        className="mt-2 w-full border border-line py-2 font-mono text-meta uppercase tracking-[0.12em] text-ink-muted transition-colors hover:border-lineHi hover:text-ink"
      >
        {flipped ? "SHOW QUESTION" : "SHOW ANSWER"}
      </button>

      <div className="mt-4 grid grid-cols-2 gap-1.5 border-t border-line pt-4 sm:grid-cols-4">
        {GRADES.map((value, index) => (
          <button
            key={value}
            type="button"
            disabled={grading}
            onClick={() => void grade(value)}
            className={`border border-line py-2 font-mono text-meta uppercase tracking-[0.12em] text-ink-muted transition-colors disabled:opacity-70 ${GRADE_STYLE[value]}`}
          >
            <span className="block">
              {index + 1} · {value}
            </span>
            {/* The real interval, not an adjective. This is what turns the bar
                into a choice rather than four unlabelled verbs. */}
            <span className="block text-micro text-ink-faint">{current.preview[value]}</span>
          </button>
        ))}
      </div>

      {done.length > 0 && (
        <button
          type="button"
          onClick={() => void undo()}
          disabled={grading}
          className="mt-2 font-mono text-meta uppercase tracking-[0.12em] text-ink-faint underline underline-offset-2 transition-colors hover:text-ink disabled:opacity-70"
        >
          ↺ undo last
        </button>
      )}
    </ActivityChrome>
  );
}
